"""Build single-file service worker (no importScripts)."""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent
BG = ROOT / 'background'
MANIFEST = ROOT / 'manifest.json'
ENTRY = BG / 'background.entry.js'
OUT = BG / 'background.js'
MODULES = [
    'messages.js',
    'page-fingerprint.js',
    'monitors.js',
]

version = '2.0.18'
if MANIFEST.is_file():
    try:
        version = json.loads(MANIFEST.read_text(encoding='utf-8')).get('version', version)
    except json.JSONDecodeError:
        pass

if not ENTRY.is_file():
    raise SystemExit('missing background/background.entry.js — run extract or edit entry file')

parts = [
    '// BUILD: %s - generated by bundle_sw.py; edit background.entry.js then re-run bundle' % version,
    "'use strict';",
    '',
]
for name in MODULES:
    path = BG / name
    if not path.is_file():
        raise SystemExit('missing module: %s' % path)
    text = path.read_text(encoding='utf-8').strip()
    parts.append('// --- %s ---' % name)
    parts.append(text)
    parts.append('')

entry = ENTRY.read_text(encoding='utf-8')
# Remove duplicate startup hooks; bundle adds them once at the end.
entry = re.sub(
    r'\nsetupOmnibox\(\);\s*$',
    '',
    entry.rstrip(),
    flags=re.MULTILINE
)
entry = re.sub(
    r'\nsetupContextMenus\(\);\s*\nsetupOmnibox\(\);\s*$',
    '',
    entry,
    flags=re.MULTILINE
)

parts.append('// --- background.entry.js ---')
parts.append(entry)
parts.append('')
parts.append('setupContextMenus();')
parts.append('setupOmnibox();')
parts.append('console.info("[link-monitor] service worker BUILD %s ready");' % version)

OUT.write_text('\n'.join(parts) + '\n', encoding='utf-8')
print('ok', OUT, 'bytes', OUT.stat().st_size, 'version', version)
